---
title: "R Notebook"
output:
  word_document: default
  html_notebook: default
---

Load the libraries

```{r}
library(clusterProfiler)
library(org.Hs.eg.db)
library(edgeR)
counts <- read.csv("Group1.csv", row.names = 1)

```

Set the factors

```{r}
treatment_pattern <- (rep(c("Untreated", "Treatment"), times = 9))
treatment <- factor(c(treatment_pattern))

donor_pattern <- c(rep("M24", times = 6), rep("M31", times = 6), rep("M32", times = 6))
donors <- factor(c(donor_pattern))

```

Cbind the factors
```{r}
groups <- data.frame(sample = colnames(counts), treatment, donors)

cbind(groups,colnames(counts))

```

1.	Visualize your library sizes.
```{r}

boxplot(colSums(counts) ~ donors)

```
```{r}
boxplot(colSums(counts) ~ treatment)
```

```{r}
boxplot(colSums(counts) ~ groups$sample)
```

```{r}
hist(log2(rowSums(counts)))
```

##3.	Determine how many genes had zero counts and remove these genes (rows) from the data set. What does your count distribution look like before and after this?##

```{r}
MinVals <- apply(counts, 1, min)
sum(MinVals == 0) 
Exp <- counts[MinVals > 0, ]
```

```{r}
ExpLog2 <- log2(Exp)
hist(rowMeans(ExpLog2), xlab = "Counts (log2)", main = "Expressed Genes")
```
##4.	Make a boxplot of log2 raw counts after removing all genes that had zero counts.## 

Plot "raw" (our log2 transformed) sample counts

```{r}
boxplot(ExpLog2, ylab = "log2 counts", main = "Raw RNA-Seq Counts", las = 2)
```

