---
title: "GrpprjctOleg"
author: "rskks"
date: "2024-07-13"
output: html_document
---

Load the data

```{r}
library(clusterProfiler)
library(org.Hs.eg.db)
library(edgeR)
counts <- read.csv("Group1.csv", row.names = 1)

```

```{r}
dim(counts)

EV <- factor(c("Untreated", "Treatment", "Untreated", "Treatment", "Untreated", "B"))
```

```{r}
# EV vs EVPA group as factors to separate 
dim(counts)

colnames <- colnames(counts)

# samples just EVPA

EVPA_pattern <- "EVPA"
EVPA_matches <- grepl(EVPA_pattern, colnames)

# Subset the original vector based on the matches
EVPA_matching <- colnames[EVPA_matches]

# View the samples that match the pattern
print(EVPA_matching)

pattern <- "^(?!.*EVPA).*$"

# Use grepl with the negative pattern
matches <- grepl(pattern, colnames, perl = TRUE)

# Subset words based on the matches
without_EVPA <- colnames[matches]

print(without_EVPA)
```

Annotate 
```{r}
column_namesEVPA <- grep("EVPA", colnames(counts), value = TRUE)
counts2 <- counts[,grep("EVPA", colnames(counts))]
counts3 <- -counts[,grep*("EVPA", )]
head(counts2)

print(column_names)
EVPAcols <- factor(column_names)
```